name: Generate PHP Stubs

on: [push]

jobs:
    generate_stubs:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    path: repos/self

            -   uses: actions/checkout@v3
                with:
                    repository: gamringer/php-pkcs11
                    ref: master
                    path: repos/php-pkcs11

            -   uses: actions/checkout@v3
                with:
                    repository: natepage/php-pkcs11-ide-helper
                    ref: main
                    path: repos/php-pkcs11-ide-helper

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none
                    extensions: pkcs11

            -   uses: ramsey/composer-install@v2
                with:
                    working-directory: repos/self

            -   run: |
                    php repos/self/bin/generate-stubs.php
                    cd repos/php-pkcs11-ide-helper
                    git config user.email "nathan.page@eonx.com"
                    git config user.name "Nathan Page"
                    git remote add upstream "https://natepage:${{ secrets.NATEPAGE_GITHUB_TOKEN }}@github.com/natepage/php-pkcs11-ide-helper.git"
                    git add .
                    git commit -m "Update stubs"
                    git push upstream main
                env:
                    NATEPAGE_GITHUB_TOKEN: ${{ secrets.NATEPAGE_GITHUB_TOKEN }}
                shell: bash
