name: Generate PHP Stubs

on: [push]

jobs:
    generate_stubs:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none
                    extensions: pkcs11

            -   uses: ramsey/composer-install@v2

            -   run: ls -la vendor

            -   uses: actions/checkout@v3
                with:
                    repository: gamringer/php-pkcs11
                    ref: master
                    path: ext/php_pkcs11

            -   run: php bin/generate-stubs.php
                shell: bash

            -   run: ls -la dist