name: Generate PHP Stubs

on: [push]

jobs:
    generate_stubs:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    path: repos/self

            -   uses: actions/checkout@v3
                with:
                    repository: gamringer/php-pkcs11
                    ref: master
                    path: repos/php-pkcs11

            -   uses: actions/checkout@v3
                with:
                    repository: natepage/php-pkcs11-ide-helper
                    ref: main
                    path: repos/php-pkcs11-ide-helper

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none
                    extensions: pkcs11

            -   uses: ramsey/composer-install@v2
                with:
                    working-directory: repos/self

            -   run: php repos/self/bin/generate-stubs.php
                shell: bash

            -   uses: actions-js/push@v1
                with:
                    author_email: "nathan.page@eonx.com"
                    author_name: "Nate Page"
                    message: "Update stubs"
                    github_token: ${{ secrets.NATEPAGE_GITHUB_TOKEN }}
                    directory: repos/php-pkcs11-ide-helper
                    repository: natepage/php-pkcs11-ide-helper
